config/routes.rb
Rails.application.routes.draw do
	root to: 'homes#top'
	get 'todolists/new'
	get 'top' => 'homes#top'
	post 'todolists' => 'todolists#create'
	get 'todolists' => 'todolists#index'
	get 'todolists/:id' => 'todolists#show', as: 'todolist'
	get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
	patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
	delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/todolist.rb
class List < ApplicationRecord::Base
  validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

  def new
  	@list = List.new
    @lists = List.all
  end

  def create
    @lists = List.all
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "Book was successfully created."
      redirect_to todolist_path(@list.id)

    else
      render "new"
    end
  end

  def index
  	@lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    flash[:success] = "Book was successfully updated."
    redirect_to todolist_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    flash[:success] = "Book was successfully destroyed."
    redirect_to todolists_new_path
  end

  private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
	印象を共有し交換することができます</p>


<%= link_to "start", todolists_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h3>Editing Book</h3>
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", todolist_path(@list.id) %> |
<%= link_to "Back", todolists_new_path %>

app/views/todolists/new.html.erb
<h1>Books</h1>

<% if flash[:success] %>
<p><%=flash[:success] %></p>
<% end %>

<table>
<thead>
<tr>
<th>title</th>
<th>body</th>
<th></th>
</tr>
</thead>

<tbody>
<% @lists.each do |list| %>
<tr>
<td>
<%= list.title %>
</td>
<td>
<%= list.body %>
</td>
<td>
<%= link_to "Show", todolist_path(list.id) %>
<%= link_to "Edit", edit_todolist_path(list.id) %>
<%= link_to "Destroy", destroy_todolist_path(list.id), method: :delete, "data-confirm" => "Are you sure?" %>
</td>
</tr>
<% end %>
</tbody>
</table>


<h3>New book</h3>

<%= form_for(@list, url: '/todolists') do |f| %>

<% if @list.errors.any? %>
<%= @list.errors.count %>errors prohibited this book from being saved:
<br>
<% @list.errors.full_messages.each do |message| %>
･<%= message %><br>
<% end %>
<% end %>

	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<br>
	<%= f.submit 'Create Book' %>
	<% end %>

app/views/todolists/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% if flash[:success] %>
<p><%=flash[:success] %></p>
<% end %>

<p>Title:</p>
<p><%= @list.title %></p>

<p>Body:</p>
<p><%= @list.body %></p>

<%= link_to "Edit", edit_todolist_path(@list.id) %> |
<%= link_to "Back", todolists_new_path %>